### PR TITLE
more "Privacy and Security Considerations" text

### PR DESCRIPTION
**Pull request by yell0wd0g**
(partially) addressing #141 -- arguably a bit delayed, but I didn't know where or how to start, so I read 
https://w3ctag.github.io/security-questionnaire/
https://www.w3.org/TR/fingerprinting-guidance/
and https://www.torproject.org/projects/torbrowser/design/#fingerprinting-linkability

@npdoty, @dontcallmedom PTAL

### CODE REVIEW

**Comment by npdoty** [comment]
Those are a very good set of documents to start from when working on security/privacy considerations. The `/TR/` version of the fingerprinting guidance is out of date, though, we are about to publish a new version and the editor's draft may be useful in terms of identifying different severity factors and mitigations:
https://w3c.github.io/fingerprinting-guidance/
Availability (https://w3c.github.io/fingerprinting-guidance/#identifying-fingerprinting-surface-and-evaluating-severity) is a factor that might be worth considering in this section of the specification: can any embedded iframe or third-party JavaScript use these features without user interaction? (In #142 I explicitly described this as drive-by available fingerprinting surface, but I'm not sure if that's still the case.)

There are a few mitigations described at the end of the new section that use "should" language, but I'm not clear on whether that's intended to be normative or not. (It seems likely that it's not.) Are there any normative mitigations that could be described, so that sites can understand that the same protections apply in all user agents?

I wasn't clear on what the suggested mitigations were for "default values". Could you explain that further?

The first example, which immediately follows the privacy and security considerations section, is an example that explicitly shows how to enumerate the UA's supported types, which seems like an explicitly bad practice and isn't showing an example driven by functionality. Limiting the number of type supported checks might be a good mitigation to recommend to those UAs that are going to support a diversity of types.

**Review by jan-ivar — APPROVED** [review]
LGTM.

**Comment by pes10k** [comment]
This doesn't seem to address @npdoty 's concerns above, specifically:

> I wasn't clear on what the suggested mitigations were for "default values". Could you explain that further?
> 
> The first example, which immediately follows the privacy and security considerations section, is an example that explicitly shows how to enumerate the UA's supported types, which seems like an explicitly bad practice and isn't showing an example driven by functionality. Limiting the number of type supported checks might be a good mitigation to recommend to those UAs that are going to support a diversity of types.

Is this intentional?  Does the WG disagree with the assessment / suggestion?

**Comment by dontcallmedom** [comment]
@pes10k I had raised it as a separate issue #196 - I don't think the WG has managed to form an opinion on it yet, but I wanted to make sure the existing progress was merged in

**Comment by pes10k** [comment]
Ah gotcha, thanks for clarifying @dontcallmedom.  That sounds good to me!

**Pull request merged**
