### PR TITLE
stop(), pause() and resume() now set state synchronously, for historical reasons.

### PR DESCRIPTION
**Pull request by jan-ivar**
Fix for https://github.com/w3c/mediacapture-record/issues/123.

### CODE REVIEW

**Comment by foolip** [comment]
Are there tests in wpt verifying this behavior?

**Comment by jan-ivar** [comment]
@foolip Not yet. We have an action item in [bug 1514016](https://bugzilla.mozilla.org/show_bug.cgi?id=1514016#c9) to provide one.

**Comment by jan-ivar** [comment]
Need to fix https://github.com/w3c/mediacapture-record/issues/150 here at the same time, otherwise `pause()` and `resume()` stop being idempotent.

**Comment by jan-ivar** [comment]
_deleted an incorrect statement_.

**Review by yell0wd0g — APPROVED** [review]
I don't see why this shouldn't be merged.

**Comment by yell0wd0g** [comment]
@jan-ivar will let you merge this one yourself seeing that there's another PR on it.

**Pull request merged**
