### PR TITLE
Update the spec link to github.io

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by yell0wd0g** [comment]
@foolip can't merge due to an error: "PR has contribution issues. The following users were unknown: @foolip.", can you take a look? Thanks.

**Comment by dontcallmedom** [comment]
@foolip to get the green light from the IPR bot, you need to be nominated to the WebRTC WG; to be nominated to the WebRTC WG, I believe your w3c account will need to be re-affiliated to Google. I believe you have 2 existing w3c accounts — can you mail me which of the two should be affiliated to Google and with what email address?

**Comment by foolip** [comment]
Sorry, that's more hoops to jump through than I want to right now, I trust someone will just indifivudally re-discover and fix this issue.

**Comment by dontcallmedom** [comment]
sorry @foolip, I hadn't noticed this was for just fixing a link; as it happened, I fixed it independently this morning.

Anyway, when you feel like getting your account fixed, let me know

**Pull request closed without merging**
